#!/bin/sh
#/etc/init.d/picast

export PATH=$PATH:/usr/local/bin
export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules

case "$1" in
  start)
  exec forever start --sourceDir=~/PiCAST -p /var/run/forever picast.js
  ;;
stop)
  exec forever stop --sourceDir=~/PiCAST picast.js
  ;;
*)
  echo "Usage: /etc/init.d/picast {start|stop}"
  exit 1
  ;;
esac

exit 0
